deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: sreedevr@andrew.cmu.edu
  password:
    secure: sPVTv/G+J4OCLSTN8jvH/2ZZANvPVtxAMbC6zCZ0/98BP8Ive40XI7Xe/eOwRcKzauBXpkZg30Ko0mvo/OCMq6zMvDxNGGImcEYXmqG101mVdOJzzr7VO3K3VuXN4/v8NGiN5MLoESYCushBcJCpdurBD15doI9WrrfZ/eCGgyQwYmU9rSWvNY/hylZOn4eofk+IHAAoX6MbbVSHejc5k10zenXhX6AEcvwfZGuxiGaUgOSDn7Icyxom3B/W1l13YOSCsYFCSSyCA2CJbC9UEquOb3I6NRBywR5sRP4CEanAalQapeh0Y9bjY1rr/stQymXoV7yWxaeChhYi7NmOEw4Xzc+u/QnMjAQTjZhx4qTbRptZbnnwMQEkuH+rK5siWFgYWdY/FWhveIE9wun2tpUFtSq/VA2j0OCsfBqmBZAp6fi+EpIpOTTRnljkPPTaRGleGKZYQ1KztAM/q0EmfrCS5JBN2vPFWXS1rLJnFK8F8I91nEtrIsHwuY3ccikG0fhio/SLxp4AdUQQ2Eb5606tRVId5czB+jRCc8HEcZpcI8tmD/18sTjoSSpdR7pAEkIvQzEnsGEfvBNPsVTjOkD+fWuYLAn7C4lTduXOULoM5qVMM9DcFgSA00+MoCVsAaLdcfyW5ruMd9CZAlwg0S7iHNQ+ODJneQqydoXjFC8=
  organization: sreedevi-cmu
  space: development
  on:
    repo: sreedevi92/Image-Gallery-Application
