language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: "./gradlew check"
deploy:
 provider: cloudfoundry
 api: https://api.run.pivotal.io
 username: sreedevr@andrew.cmu.edu
 password:
   secure: jnYDwKz0dmNWc5704NM+zo5313oVfdmSdK0G9dRvUcxhlhE1/wVzOl1MJKzo6vVw6rAGLMMv1XhoNq25SnHeM60fa0f11Mn9HjDRQ8ER0ODCr4AXxJlKAuk4aK1TFssqMp5FKrazq3KK1pDOfTrAjoMaimvZbO9E9CB93tPsWicqAmFZk2T4HXtpQc2NiQv7aToBs6N/OtJEJgAPlgkCLTms2gifKF4dO3vraLORlOKxxxb4wAtvZGHqKuuY1aiFQd6iI2eDjVBm7Z8jMOmqQagKMV78nrDEmoSuGj3/oM21m3355pakREVg16hGLcwpOwgItBS1GeWmBv4NbOKy3iOeSjdbdFz4hFOeIFRL/Xa1Cl2XS5pPkym+GNAkezX5Sr0SKgbmZCFKtRwRJx1xgAUQXTM6+/5HsMysg0VryRqFVE9tI0o7Ei30XhtYbZoVnFHb35zdcWTCDu0ESagdw7GoYfyerYr/S1MT9DkZzQ+kfA6YqDj/E4qBZXTWfUF8/NQJ4iudM79uBQxyuPiQCpWr4E94wsLn6fjNXEiyy+HGNfXv0XyyNlOPxwh8Tupp0JZmauW9j1i8pn+9e76P7RzzM9Sn4SyQ3LV1V2v2bbRhiKTWj7i27cCTa6Q3S9MteAzkWsBFVvDqRaBUbdu/bcC4WFEfzveyzj2b5Ok78AQ=
 organization: sreedevi-cmu
 space: development
 on:
   repo: sreedevi92/Image-Gallery-Application
