language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: "./gradlew check"
deploy:
 edge: true
 provider: cloudfoundry
 api: https://api.run.pivotal.io
 username: sreedevr@andrew.cmu.edu
 password: $cooByDoo009

 organization: sreedevi-cmu
 space: development
 on:
   repo: sreedevi92/Image-Gallery-Application
