language: java
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: sreedevr@andrew.cmu.edu
  password:
    secure: oYY/ilTwcSVR/Cf3b/dMx37noenxeFEEUr55jFgtwSP0MHMDVxnpC5HPyaalSHqZ9WZ06h2Z+pldX9eLADDw2sby1UjefM6cN7sPTRtNOiufv1RWif4K7iuP4V1Q56p4laSGwUqRwbSGGV8wNUzMEwAoUHV7SKXrBCR5juTNxf3YomDegneKXLyHKdFds/U5RrbHbBUxCwwVxBvechNM/3cAQKPr0whMkIdahQj6Sh17WqSlK2T2mBDMa12J3Vb1c+tTzgc4zg3GusGkE9145VmOG521xej8ueKF52EMdadwghRL7OqDUiNQ4wEE5ZFPSX3JDhTITcqszpGaC54hEW6GJxE31HZt7yvemCyBf52i+TWo1lWmQyuBQcDZTslUEmM8jNNZRwQS2P9WX3IRofmDUHidSSO1DU/CAjl0cGXtPeDkb4vNlHe7skofIlxbMfXL2i+owvy8XFP5OV0orrCLZXqu417bpkJiRLsRufh7wS0PSHsToD6/n4JFi+rBZPjFKvzi2MfdGOpOWgo4up64Y8fn9H5fSDM1Xy9Dx1dNCd6ekD2odcRy+TJFn5MbFYPaMVIF/nrOY3C9jrtZEmlgqUz7qFJXnanQLwgJql7vs/lrjLZme5p6B0zgj92ZUTOVy5AfwMjFpzCIgwHXIvw00I7E3HwzDlk1On/gGcU=
  organization: sreedevi-cmu
  space: development
  on:
    repo: sreedevi92/Image-Gallery-Application
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- oraclejdk8
