language: java
deploy:
   edge: true
   provider: cloudfoundry
   username: sreedevr@andrew.cmu.edu
   password: riseandshine06
   api: https://api.run.pivotal.io
   organization: myawesomeorganization
   space: staging
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
