language: java
deploy:
  edge: true
  provider: cloudfoundry
  username: "<myCloudfoundaryUsername>"
  password:
    secure: "b72lKqy7+oZ+BDl0o/oINu5Z20MIr8tMilouQ5SWSGl3qBMEwvYgdk/hDkGVWjk763BKiDnXiaD23OO5LtUgBbxvXixCZklkYnPWmP+0uWZcf8HwyxAiATtK/DZYpZvQuwjrVR1Md6PJMx9vAnC31GL/6aKn+scz0WRwyQGmmcX8COPuaElF6cjoXoe9DGDlZ92WR8yzBTibb23PTzg3pwKix37yywk+u8g6W1mBoSXhw4ibnuNqvzZQl+YDiFfx887a0c/YHdIrXkSDcfXmGS3uXAb0S/C0b61K7DHoaicPuevlh2I+Y+MmPfLENinZyTuSaWd/e1bnqLroFmwpHuSDf89f3E+/0/0kJNS3IzuMMm18ZHJqPybtuajJihHImRibaVcQtPlNCNL9pUfaunvtybFDqxT1INE1KR7m6MT1bP5hfgTah9NqY7cCREh+AuipKmopITch8rqDPJ4Y7L+5EslRlS83g0j+/m5sdmikoAdmoPXJM1ReXbDiW+CD3YcaUKMQT8UkGxU2B2wYSZj90a6eSXAkczoC8wQC7N9AV5nqAgjTns0GWGSLYKU0Qpk4mZYl8ooYnWM5eKZP8DpvNqjRHXKoqsssWsTKD1oFLP124MCvjJ8yaU7VfSR08vBeoZ6Df09m8FVP5o9BeRQZqlh5mnVWCGN+MdVd2cw="
  api: https://api.run.pivotal.io
  organization: sreedevi-cmu
  space: development
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
